### ISSUE TITLE
No way to enter DFU

### ISSUE THREAD

**Issue by antoinealb** [cvra/uwb-beacon-board#1]
It would be nice to be able to program the board using only the USB connection, through built in DFU bootloader. Adding a small switch or button for this would be nice.

**Comment by SyrianSpock** [comment]
The current revision has BOOT0 wired to ground, so the board can't be modified easily.

**Comment by romaincvra** [comment]
Just use the CAN bootloader... Colinet

**Comment by antoinealb** [comment]
> The current revision has BOOT0 wired to ground, so the board can't be modified easily.

I know.  Just something to keep in mind for revB.

> Just use the CAN bootloader... Colinet

Precisely, I need the DFU bootloader to install the CAN bootloader 😉

**Comment by antoinealb** [comment]
This will require rewiring of the STATUS_LED signal, as it is currently connected to boot1.
