### ISSUE TITLE
UWB module reset pin is driven by USB peripheral

### ISSUE THREAD

**Issue by antoinealb** [cvra/uwb-beacon-board#2]
Out of the usual engineering bad luck, we assigned the UWB's reset pin to a pin used by the USB FS PHY module (see enclosed picture). This means the module was always held into reset (RSTn was at ~1V) and never answered over SPI. 😢 When I disabled USB completely (using UART for shell), I was able to get it working right away.

Of course there might be a way to fix this in software, but since we have a lot of unused pins on the microcontroller, we might as well re-route it to a different pin not affected by this issue.

<img width="600" alt="problem_vbus" src="https://user-images.githubusercontent.com/2419961/31186766-e7c63e2e-a92f-11e7-8f64-32154f585943.png">

**Comment by SyrianSpock** [comment]
Well, that's unfortunate. We can fix that in the next version. So it's not possible to use USB at all ? Otherwise I can rework the PCBs to reroute the trace that causes problems.

**Comment by antoinealb** [comment]
I could not make USB and UWB module work at the same time. For now I worked around it by disabling USB and using UART. I can discuss it with my supervisor tomorrow to see if he has an idea, otherwise we can probably cut the trace and solder a wire to another pin.

**Comment by SyrianSpock** [comment]
That's what I was suggesting, but can't you disable the VBUS function while still using USB ? I know that you can tell ChibiOS to ignore VBUS, but I don't know how to avoid overriding the alternate function.

**Comment by antoinealb** [comment]
So ChibiOS clearly doesn't support removing the alternate function of the pin, and I am not sure if its even possible given the USB PHY.

VBUS is already ignored by the way, since it is not connected.

**Comment by SyrianSpock** [comment]
Fair enough.

"Marcel, fait chauffer le fer !"

![](http://s2.quickmeme.com/img/72/72e7a56539c48b05dd79f2158d7c85f456d0fca22ba91e992fd699f3c2ffe4a3.jpg)

**Comment by antoinealb** [comment]
So after discussion, the best would be to wire PA9 to actual VBus, because on some hosts it does not work properly without it and use another pin for UWB_RST

**Comment by antoinealb** [comment]
Tested it tonight: reworked a board to remove connection between UWB_RST and PA9,  and USB works at the same time as UWB. yay.
